### PR TITLE
Done :D

### PR DESCRIPTION
**Pull request by Dannyx1604**
I think you are going to change the favicon and the MOTD of the ping message

### CODE REVIEW

**Comment by Dannyx1604** [comment]
wait I forgot to add one commit

**Comment by Masu-Baumgartner** [comment]
Hey hey, we dont want your custom motd in here. Sorry. Please remove it

**Comment by Masu-Baumgartner** [comment]
also your input reading implementation is not optimal

**Comment by Dannyx1604** [comment]
> also your input reading implementation is not optimal

I think that this is the easiest way to do it..?

**Comment by Masu-Baumgartner** [comment]
It is not

**Comment by Dannyx1604** [comment]
Is this the easiest way for the function?


private static void MonitorUserInput() 
{ 
    while (Console.ReadLine()?.ToLower() != "stop") ;
    Logger.Info("Stopping the program...");
    Listener.Stop(); 
}

**Pull request closed without merging**
